### ISSUE TITLE
Is the local API rate-limited?

### ISSUE THREAD

**Issue by solid-pixel** [wez/govee-lan-hass#10]
Hello, and thank you SO MUCH for this fantastic integration, it's so much better than the cloud one :)

I was under the impression that since this is local, there wouldn't be any rate limits, but I sometimes bump into this error if I change things a bit too quickly:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/18260178/212535164-ec13dfe9-a4b3-4b6e-92d2-2a320e58a119.png">

Is this the expected behavior, or am I doing something wrong with my setup?

Thanks!

**Comment by wez** [comment]
Not as far as I know, but it's possible that you're not actually using the lan API and the HTTP API is being used instead.
In a recent commit I added some additional state attributes that might provide a little bit of insight.

In HASS, go to "Developer Tools" -> "State", then type in the name of the light you were trying to control; it should show something like this screenshot; please share what you see.

![image](https://user-images.githubusercontent.com/117777/212545829-e0d2dc54-20f3-44bf-ac25-6bc679c76583.png)

You could try putting this snippet into your `configuration.yaml` and restarting HASS; that will increase logging and hopefully tell us a bit more about what actually happened:

```yaml
logger:
  logs:
    custom_components.govee_lan: debug
    govee_led_wez: debug
```

**Comment by solid-pixel** [comment]
hey @wez really sorry for the late reply, I was crazy busy with work!
And thanks a lot for the thorough response!

Here's the output, which indeed shows `lan_enabled: false` 🤔

```
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 9000
min_mireds: 111
max_mireds: 500
supported_color_modes: brightness, color_temp, rgb
color_mode: rgb
brightness: 22
hs_color: 349.412, 100
rgb_color: 255, 0, 45
xy_color: 0.683, 0.291
http_enabled: true
ble_enabled: false
lan_enabled: false
update_status: ok at Tue Jan 17 21:06:49 2023
timeout_count: 0
icon: mdi:sine-wave
friendly_name: Neon
supported_features: 0
```

The LAN Control switch is set to ON in the Govee app.

Thanks again!

**Comment by wez** [comment]
Try turning up the debugging per my earlier comment to see why it doesn't show up as LAN enabled?
It could be a networking issue: is the device on the same subnet as hass?
Are there settings in your wifi AP/router that might prevent/interfere with multicast UDP?

**Comment by solid-pixel** [comment]
@wez yes sorry I was actually doing it right now but you beat me :D 

This is the log from boot until I hit the rate limit, with debug enabled:

```bash
2023-01-17 21:22:05.549 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frank_energie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.550 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.550 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.551 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration govee_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.551 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.552 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration petkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.553 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:05.553 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-17 21:22:08.774 ERROR (MainThread) [homeassistant.components.media_player] The androidtv platform for the media_player integration does not support platform setup. Please remove it from your config.
2023-01-17 21:22:09.618 ERROR (MainThread) [homeassistant.components.binary_sensor] rpi_power: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/rpi_power/binary_sensor.py", line 53, in update
    value = self._under_voltage.get()
AttributeError: 'NoneType' object has no attribute 'get'
2023-01-17 21:22:14.020 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]
2023-01-17 21:22:14.023 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Pina' for tapo integration not ready yet: Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]; Retrying in background
2023-01-17 21:22:16.041 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.2.105; Retrying in background in 30 seconds
2023-01-17 21:22:16.526 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.iphone_di_giada_battery_state_2 (<class 'homeassistant.components.mobile_app.sensor.MobileAppSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('battery') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mobile_app%22
2023-01-17 21:22:16.804 ERROR (MainThread) [snitun.client.client_peer] Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes)
2023-01-17 21:22:16.807 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2023-01-17 21:22:19.216 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LINKSYS-AX4200' for upnp integration not ready yet: Device not discovered: uuid:ebf5a0a0-1dd1-11b2-a90f-d8ec5edfb214::urn:schemas-upnp-org:device:InternetGatewayDevice:2; Retrying in background
2023-01-17 21:22:24.710 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]
2023-01-17 21:22:38.022 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]
2023-01-17 21:23:01.575 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]
2023-01-17 21:23:44.714 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]

//////////////////////////////////////////////////////////////////////////
       GOVEE STUFF SEEMS TO START HERE
//////////////////////////////////////////////////////////////////////////

2023-01-17 21:24:49.621 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140004208786640] failed to control device: Rate limit exceeded, retry in 52 seconds.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 570, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/govee_lan/light.py", line 319, in async_turn_on
    await self._govee_controller.set_brightness(
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 683, in set_brightness
    await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/http.py", line 105, in http_device_control
    raise RuntimeError(f"failed to control device: {message}")
RuntimeError: failed to control device: Rate limit exceeded, retry in 52 seconds.
2023-01-17 21:25:08.038 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Error communication with API: Cannot connect to host 192.168.0.199:80 ssl:default [Connect call failed ('192.168.0.199', 80)]
```

> It could be a networking issue: is the device on the same subnet as hass?

Mmmh yes technically, but I run HASS in docker so that might be why, I'm gonna mess around with the docker network a bit and see if it helps!

**Comment by solid-pixel** [comment]
@wez I got it!
I had to put HASS' docker container in `network_mode: host`, which now allows the `lan_enabled:` to show up as `true` again :)

Thanks so much for pointing me to the right direction 👍

**Comment by wez** [comment]
Thanks for confirming; I added a note about this to https://github.com/wez/govee-lan-hass/blob/main/README.md#requirements-of-the-lan-api
