### ISSUE TITLE
Exception when adding integration

### ISSUE THREAD

**Issue by NewmanIsTheStar** [wez/govee-lan-hass#17]
Pop up Error says: **Config flow could not be loaded: {"message":"Invalid handler specified"}**

Log follows

2023-02-23 21:24:51.851 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-23 21:24:51.853 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-23 21:24:51.854 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration govee_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-23 21:25:25.688 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.govee_lan.config_flow
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 790, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/home/homeassistant/.homeassistant/custom_components/govee_lan/config_flow.py", line 15, in <module>
class GoveeFlowHandler(config_entries.ConfigFlow, domain=DOMAIN):
File "/home/homeassistant/.homeassistant/custom_components/govee_lan/config_flow.py", line 20, in GoveeFlowHandler
self, user_input: dict[str, Any] | None = None
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2023-02-23 21:25:25.695 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration govee_lan: Exception importing custom_components.govee_lan.config_flow

**Comment by ilboud** [comment]
I have the same issue

**Comment by danyknight** [comment]
Did you figure out a way around this?

**Comment by NewmanIsTheStar** [comment]
No.  I avoided the problem by programming up a Raspberry Pi Pico W ($6) to control the light.  Shockingly easy.  Literally took 10 minutes to look up the protocol and adapt one of the Pico SDK examples with no prior knowledge.

**Comment by wez** [comment]
I think that error is because your python version is too old and it doesn't understand the typing syntax.
The latest version of HA requires a much newer version of python than 3.9
