### ISSUE TITLE
govee strips disconnecting

### ISSUE THREAD

**Issue by Adaaks** [wez/govee-lan-hass#26]
hey sorry to bother but i think i found something to fix the strips.

Logger: homeassistant.helpers.entity
Source: custom_components/govee_lan/light.py:420
Integration: Govee LAN Control ([documentation](https://github.com/wez/govee-lan-hass), [issues](https://github.com/wez/govee-lan-hass/issues))
First occurred: 01:09:48 (3 occurrences)
Last logged: 01:10:48

Update for light.strips fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/govee_lan/light.py", line 420, in async_update
    await self._govee_controller.update_device_state(self._govee_device)
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 299, in update_device_state
    self._request_lan_status(device.lan_definition)
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 270, in _request_lan_status
    self._send_lan_command(
  File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 266, in _send_lan_command
    dgram_socket.bind((self.lan_source_address, 0))
OSError: [Errno 99] Address not available

**Comment by Adaaks** [comment]
> Sounds like your IP address is changing. Make sure that your home assistant machine has a static IP address!

it's static, my ip to go to home assistant is always the same.

i have a wifi tuya bulb connected to ha, and it works everytime, compared to the wifi govee strips which disconnect.

**Comment by wez** [comment]
The `dgram_socket.bind((self.lan_source_address, 0))` line is trying to use the IP address that was used when hass was started up. That error message suggests that that IP address is no longer available.
It sounds like there is something weird happening with the networking on that system, but there is no information here that I can use to suggest what.
